/* eslint-disable import/prefer-default-export */
export const page1 = {
  reviews: [
    {
      parents: [{ id: '96e83a90-48da-4e81-9d06-7f1b76e5364e' }],
      id: 'a8f5843e-2229-42b6-ae27-32a49ef539ca',
      traveledWith: 'FAMILY',
      entryDate: 1472717951673,
      travelDate: 1470009600000,
      ratings: {
        general: { general: 8 },
        aspects: {
          location: 9,
          service: 0,
          priceQuality: 8,
          food: 0,
          room: 0,
          childFriendly: 9,
          interior: 0,
          size: 0,
          activities: 0,
          restaurants: 0,
          sanitaryState: 0,
          accessibility: 0,
          nightlife: 0,
          culture: 0,
          surrounding: 0,
          atmosphere: 0,
          noviceSkiArea: 0,
          advancedSkiArea: 0,
          apresSki: 0,
          beach: 0,
          entertainment: 0,
          environmental: 0,
          pool: 6,
          terrace: 0,
        },
      },
      titles: { en: 'Accommodation fabulous, loads space, few cars' },
      texts: {
        en:
          'Pool a bit disappointing for my 10 and 12 year olds. Slides slow and land in very shallow water\nI think for younger the pools would be fabulous',
      },
      user: 'rachel abbott',
      locale: 'en',
    },
    {
      parents: [{ id: '96e83a90-48da-4e81-9d06-7f1b76e5364e' }],
      id: '15c4dd9a-3713-4242-9be1-26dd382ae0fe',
      traveledWith: 'FRIENDS',
      entryDate: 1472639278470,
      travelDate: 1470009600000,
      ratings: {
        general: { general: 9 },
        aspects: {
          location: 9,
          service: 0,
          priceQuality: 9,
          food: 0,
          room: 0,
          childFriendly: 9,
          interior: 0,
          size: 0,
          activities: 0,
          restaurants: 0,
          sanitaryState: 0,
          accessibility: 0,
          nightlife: 0,
          culture: 0,
          surrounding: 0,
          atmosphere: 0,
          noviceSkiArea: 0,
          advancedSkiArea: 0,
          apresSki: 0,
          beach: 0,
          entertainment: 0,
          environmental: 0,
          pool: 9,
          terrace: 0,
        },
      },
      titles: { en: 'Fantastic we come back every year' },
      texts: {
        en:
          'Everything is clean, the people are friendly. The only thing we miss is (free) wifi all over de campingplace',
      },
      user: 'P. van der Pluijm',
      locale: 'en',
    },
    {
      parents: [{ id: '96e83a90-48da-4e81-9d06-7f1b76e5364e' }],
      id: 'e54b1d94-5590-4410-9d4e-76b3ea1f2ce5',
      traveledWith: 'COUPLE',
      entryDate: 1472550180580,
      travelDate: 1470009600000,
      ratings: {
        general: { general: 10 },
        aspects: {
          location: 10,
          service: 0,
          priceQuality: 9,
          food: 0,
          room: 0,
          childFriendly: 9,
          interior: 0,
          size: 0,
          activities: 0,
          restaurants: 0,
          sanitaryState: 0,
          accessibility: 0,
          nightlife: 0,
          culture: 0,
          surrounding: 0,
          atmosphere: 0,
          noviceSkiArea: 0,
          advancedSkiArea: 0,
          apresSki: 0,
          beach: 0,
          entertainment: 0,
          environmental: 0,
          pool: 10,
          terrace: 0,
        },
      },
      titles: { en: 'Great camping site' },
      texts: { en: 'Friendly staff - nice restaurants and Sporting Bar' },
      user: 'Claus Duus Pedersen',
      locale: 'en',
    },
    {
      parents: [{ id: '96e83a90-48da-4e81-9d06-7f1b76e5364e' }],
      id: '09844c8f-f96a-4626-8b83-6e9ef0db5c89',
      traveledWith: 'FAMILY',
      entryDate: 1472384079410,
      travelDate: 1470009600000,
      ratings: {
        general: { general: 9 },
        aspects: {
          location: 8,
          service: 0,
          priceQuality: 8,
          food: 0,
          room: 0,
          childFriendly: 8,
          interior: 0,
          size: 0,
          activities: 0,
          restaurants: 8,
          sanitaryState: 8,
          accessibility: 0,
          nightlife: 0,
          culture: 0,
          surrounding: 0,
          atmosphere: 0,
          noviceSkiArea: 0,
          advancedSkiArea: 0,
          apresSki: 0,
          beach: 0,
          entertainment: 0,
          environmental: 0,
          pool: 7,
          terrace: 0,
        },
      },
      titles: { nl: 'Enorm genoten' },
      texts: {
        nl:
          'Door de brand uit moeten wijken naar andere to, hadden uiteindelijk caravan van Oostenrijkse to. Enorm goed bevallen we zaten in een gezellig straatje, prima camping, overal vriendelijk personeel, prima beveiliging, camping komt niet zo groot over, s avonds gezellige sfeer bij de restaurants, winkels ed, zwembad vonden wij minder omdat er voor oudere kinderen te weinig glijbanen waren en het er onoverzichtelijk is, dus dagelijks naar strand waar je je prima kon vermaken. Supermarkt op camping is groot, wil je meer/ goedkoper dan zit er op 5 min rijden een grote supermarkt. Behalve caorle niets te zien in de omgeving, maar dat wisten we. Voor een zon, zee, strand vakantie zit je hier echter prima!',
      },
      user: 'Ursula van Oirschot',
      locale: 'nl',
    },
    {
      parents: [{ id: '96e83a90-48da-4e81-9d06-7f1b76e5364e' }],
      id: '98655f13-a610-443e-a039-633f2ee322f9',
      traveledWith: 'FAMILY',
      entryDate: 1471630264527,
      travelDate: 1470009600000,
      ratings: {
        general: { general: 9 },
        aspects: {
          location: 8,
          service: 0,
          priceQuality: 8,
          food: 0,
          room: 0,
          childFriendly: 9,
          interior: 0,
          size: 0,
          activities: 0,
          restaurants: 8,
          sanitaryState: 7,
          accessibility: 0,
          nightlife: 0,
          culture: 0,
          surrounding: 0,
          atmosphere: 0,
          noviceSkiArea: 0,
          advancedSkiArea: 0,
          apresSki: 0,
          beach: 0,
          entertainment: 0,
          environmental: 0,
          pool: 9,
          terrace: 0,
        },
      },
      titles: { nl: 'Relaxte vakantie voor het hele gezin!' },
      texts: {
        nl:
          'Camping is groot,maar dit is nietv te merken. Schoon, fijn zwembad en strand, altijd een bedje te krijgen al kost dit wel 8,00-9,00 euro per dag voor 2 bedjes en een parasol. Allerlei winkeltjes en restaurantjes op de camping ,caorle en lido di jesolo dichtbij en gezellig sávonds. Voor zowel kinderen en pubers is er genoeg te doen. Dochter van 16 jaar ging iedere avond naar de disco waar zij nederlandse leeftijdsgenoten ontmoette. Onze zoon van 13 jaar ging iedere ochtend naar de voetbalschool. Het enige nadelen waren de vele muggen, onze chalet helemaal achterin stond aan een stoffig laantje, terwijl er vele mooie nette andere locaties waren die bestraat waren en centraler stonden. Al met al een heerlijke vakantie gehad met super mooi weer.',
      },
      user: 'a van der starre',
      locale: 'nl',
    },
  ],
  pagination: { numPages: 40, start: 0, limit: 5, length: 200 },
};

export const page2 = {
  reviews: [
    {
      parents: [{ id: '96e83a90-48da-4e81-9d06-7f1b76e5364e' }],
      id: 'd50e1d42-0994-4025-8d9e-70e6dc35f314',
      traveledWith: 'FAMILY',
      entryDate: 1471607701880,
      travelDate: 1467331200000,
      ratings: {
        general: { general: 8 },
        aspects: {
          location: 6,
          service: 0,
          priceQuality: 7,
          food: 0,
          room: 0,
          childFriendly: 9,
          interior: 0,
          size: 0,
          activities: 0,
          restaurants: 7,
          sanitaryState: 7,
          accessibility: 0,
          nightlife: 0,
          culture: 0,
          surrounding: 0,
          atmosphere: 0,
          noviceSkiArea: 0,
          advancedSkiArea: 0,
          apresSki: 0,
          beach: 0,
          entertainment: 0,
          environmental: 0,
          pool: 8,
          terrace: 0,
        },
      },
      titles: { nl: 'Heel leuk, kindvriendelijk park !' },
      texts: {
        nl:
          'Hele  slechte bedden in de classic  sta caravans van touroperator.\nHoud rekening met veel muggen.',
      },
      user: 'anelies jongen',
      locale: 'nl',
    },
    {
      parents: [{ id: '96e83a90-48da-4e81-9d06-7f1b76e5364e' }],
      id: '5d9ed26c-8310-4822-b16a-b28544185f26',
      traveledWith: 'FAMILY',
      entryDate: 1470829218617,
      travelDate: 1470009600000,
      ratings: {
        general: { general: 6 },
        aspects: {
          location: 8,
          service: 0,
          priceQuality: 5,
          food: 0,
          room: 0,
          childFriendly: 8,
          interior: 0,
          size: 0,
          activities: 0,
          restaurants: 7,
          sanitaryState: 6,
          accessibility: 0,
          nightlife: 0,
          culture: 0,
          surrounding: 0,
          atmosphere: 0,
          noviceSkiArea: 0,
          advancedSkiArea: 0,
          apresSki: 0,
          beach: 0,
          entertainment: 0,
          environmental: 0,
          pool: 8,
          terrace: 0,
        },
      },
      titles: { nl: 'Voor ons niet meer' },
      texts: {
        nl:
          'Wij hadden meer verwacht van deze camping gezien de beoordeling. Het zwembad is top en het strand (direct eraan) is super. De camping heeft totaal geen sfeer en mega massaal. Personeel chagrijnig en erg commercieel. De zonnebedden heel duur en de attracties vd kids ook. Peuterspeeltuin 5 euro per kind. Daarnaast stikte het vd muggen maar daar heb je op meer campings last van. Caorle is wel een heel leuk stadje. Voor ons volgende keer weer een camping aan het gardameer oid, veel meer italiaanse sfeer!',
      },
      user: 'Kim v hagen',
      locale: 'nl',
    },
    {
      parents: [{ id: '96e83a90-48da-4e81-9d06-7f1b76e5364e' }],
      id: 'a56037da-c378-4e1a-b85c-2c52a1931217',
      traveledWith: 'FAMILY',
      entryDate: 1470429163297,
      travelDate: 1467331200000,
      ratings: {
        general: { general: 9 },
        aspects: {
          location: 7,
          service: 0,
          priceQuality: 7,
          food: 0,
          room: 0,
          childFriendly: 10,
          interior: 0,
          size: 0,
          activities: 0,
          restaurants: 9,
          sanitaryState: 9,
          accessibility: 0,
          nightlife: 0,
          culture: 0,
          surrounding: 0,
          atmosphere: 0,
          noviceSkiArea: 0,
          advancedSkiArea: 0,
          apresSki: 0,
          beach: 0,
          entertainment: 0,
          environmental: 0,
          pool: 9,
          terrace: 0,
        },
      },
      titles: { 'nl-be': 'Volgend jaar weer' },
      texts: {
        'nl-be':
          'Wat een geweldige camping is dit. Geen knusse camping maar meer een vakantiedorp! Moet je wel van houden natuurlijk......\nOnze kids hebben zich supergoed vermaakt met de animatie (topteam), kidsclub en minidisco!! Hopelijk is deze animatiegroep er volgend jaar weer, want de kids willen terug!!!\nMuggen zijn er wel, maar goed insmeren met een anti muggen middel scheelt al een hoop leed. Sanitair is superschoon (soms wel wachtrijen bij de douches). \nZwembad is top, alleen jammer dat er geen stukje bad is wat diep is, je kunt echt overal staan. En ligbedjes bij het zwembad met 3 kids voor 3 weken is niet te betalen, wel plaats op het gras. \nAl met al hebben wij een supervakantie gehad en gaan we voor het eerst voor een 2e keer terug naar een camping. \nTip: Stepje of fietsje is geen overbodige luxe!!',
      },
      user: 'Beste fam. van Pra Delle Torri juli 2016',
      locale: 'nl-be',
    },
    {
      parents: [{ id: '96e83a90-48da-4e81-9d06-7f1b76e5364e' }],
      id: 'd610360d-b8a7-44aa-8bf6-e178049d68e6',
      traveledWith: 'COUPLE',
      entryDate: 1469485687883,
      travelDate: 1409529600000,
      ratings: {
        general: { general: 10 },
        aspects: {
          location: 10,
          service: 0,
          priceQuality: 10,
          food: 0,
          room: 0,
          childFriendly: 10,
          interior: 0,
          size: 0,
          activities: 0,
          restaurants: 10,
          sanitaryState: 10,
          accessibility: 0,
          nightlife: 0,
          culture: 0,
          surrounding: 0,
          atmosphere: 0,
          noviceSkiArea: 0,
          advancedSkiArea: 0,
          apresSki: 0,
          beach: 0,
          entertainment: 0,
          environmental: 0,
          pool: 10,
          terrace: 0,
        },
      },
      titles: { nl: 'Fantastisch' },
      texts: {
        nl:
          'Alles was prima,heel erg vriendelijk personeel,goede restaurants.\nEen fantastisch "vakantiedorp"',
      },
      user: 'R. Winters',
      locale: 'nl',
    },
    {
      parents: [{ id: '96e83a90-48da-4e81-9d06-7f1b76e5364e' }],
      id: '139c1947-534d-459a-af14-316ba3ec5862',
      traveledWith: 'FRIENDS',
      entryDate: 1469449089483,
      travelDate: 1467331200000,
      ratings: {
        general: { general: 8 },
        aspects: {
          location: 9,
          service: 0,
          priceQuality: 6,
          food: 0,
          room: 0,
          childFriendly: 9,
          interior: 0,
          size: 0,
          activities: 0,
          restaurants: 0,
          sanitaryState: 0,
          accessibility: 0,
          nightlife: 0,
          culture: 0,
          surrounding: 0,
          atmosphere: 0,
          noviceSkiArea: 0,
          advancedSkiArea: 0,
          apresSki: 0,
          beach: 0,
          entertainment: 0,
          environmental: 0,
          pool: 8,
          terrace: 0,
        },
      },
      titles: { cz: 'Fantasticky kemp' },
      texts: {
        cz:
          'Krásný kemp, stále všude cisto. Super parkování pro karavan. Blízko u moře. Prostorná pláž.  Úžasná restaurace. Výborně zásobený obchod. Skvělé golfové hřiště . Zábavní atrakce pro děti.',
      },
      user: 'Klára Halešová',
      locale: 'cz',
    },
  ],
  pagination: { numPages: 40, start: 5, limit: 5, length: 200 },
};
